services:
  webapp:
    image: com.dziem/popapi
    env_file: "src/main/resources/private/webapp.env"
    volumes:
      - ./src/main/resources/application-docker.properties
    ports:
      - "8080:8080"
