package com.dziem.popapi.model;

public enum Mode {
    COUNTRIES_1900,
    COUNTRIES_1939,
    COUNTRIES_1989,
    COUNTRIES_NORMAL,
    COUNTRIES_FUTURE,
    COUNTRIES_CHAOS,
    SPOTIFY_TOP_ARTISTS,
    SPOTIFY_TOP_SONGS_GENERAL,
    SPOTIFY_TOP_SONGS_HIP_HOP,
    SPOTIFY_TOP_SONGS_ROCK,
    FORMULA_TOP_SCORE,
    APARTMENTS_WORLD,
    APARTMENTS_POLAND,
    SPOTIFY_TOP_SONGS_POP,
    HISTORY,
    SOCIAL_MEDIA_TWITTER,
    SOCIAL_MEDIA_INSTAGRAM,
    SOCIAL_MEDIA_TIK_TOK,
    SOCIAL_MEDIA_YOUTUBE,
    MOVIES,
    TV_SHOWS,
    FORMULA_TOP_DRIVERS_PODIUMS,
    FORMULA_TOP_DRIVERS_FASTEST_LAPS,
    CELEBS
}
