package com.dziem.popapi.model;

public enum Mode {
    COUNTRIES_1900,
    COUNTRIES_1939,
    COUNTRIES_1989,
    COUNTRIES_NORMAL,
    COUNTRIES_FUTURE,
    COUNTRIES_CHAOS,
    SPOTIFY_TOP_ARTISTS,
    SPOTIFY_TOP_SONGS_GENERAL,
    SPOTIFY_TOP_SONGS_HIPHOP,
    SPOTIFY_TOP_SONGS_ROCK,
    SPOTIFY_TOP_SONGS_POP
}
